[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyscreen"
version = "1.0.0"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3"
]

[project.scripts]
pyscreen = "pyscreen.__main__:main"
